// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrAuLiwzfCOfroYxiTca_fWhQb-Ww1-o8',
    appId: '1:703738040310:web:96a5c01a21501ce5b741d7',
    messagingSenderId: '703738040310',
    projectId: 'todolist-11386',
    authDomain: 'todolist-11386.firebaseapp.com',
    storageBucket: 'todolist-11386.appspot.com',
    measurementId: 'G-XH9YKHJ4VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCetU_0pju41HOj3E5GvfhbLFDUSxtRCxM',
    appId: '1:703738040310:android:0dbc3d12164ae76fb741d7',
    messagingSenderId: '703738040310',
    projectId: 'todolist-11386',
    storageBucket: 'todolist-11386.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKxO1X-NW9UlFDxUHau3Nt0cZk216VoZc',
    appId: '1:703738040310:ios:fe26827de028934db741d7',
    messagingSenderId: '703738040310',
    projectId: 'todolist-11386',
    storageBucket: 'todolist-11386.appspot.com',
    iosClientId: '703738040310-an1aea3h8ol67sjvis30c9hp2uich80k.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );
}
